# Базовий образ з Python 3.11
FROM python:3.11-slim

# Встановимо системні залежності
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо всі файли проєкту
COPY . .

# Оновлення pip і встановлення залежностей
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Встановлюємо порт, який надасть Render
ENV PORT=8080

# Команда запуску
CMD ["python", "main.py"]
